---
- name: Criar VPC
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Criar uma nova VPC
      amazon.aws.ec2_vpc_net:
        name: "MinhaVPC"
        cidr_block: "10.10.0.0/16"
        region: us-east-1
        state: present
        tags:
          Name: "VpcProject"
      register: vpc
